module.exports = {
  plugins: [
    "cleanupAttrs",
    "cleanupEnableBackground",
    "cleanupIDs",
    "cleanupNumericValues",
    "collapseGroups",
    "convertColors",
    "convertEllipseToCircle",
    "convertPathData",
    "convertShapeToPath",
    "convertStyleToAttrs",
    "convertTransform",
    "inlineStyles",
    "mergePaths",
    "minifyStyles",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "removeComments",
    "removeDesc",
    "removeDoctype",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeHiddenElems",
    "removeMetadata",
    "removeNonInheritableGroupAttrs",
    "removeTitle",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    "removeXMLProcInst",
    "sortDefsChildren",
    // custom
    "prefixIds",
    "removeDimensions",
    "removeRasterImages",
    "removeScriptElement",
    "removeStyleElement",
    "sortAttrs",
    {
      name: "removeAttrs",
      params: {
        attrs: "(fill|stroke)",
      },
    },
    {
      name: "removeUnknownsAndDefaults",
      params: {
        keepRoleAttr: true,
      },
    },
    {
      name: "removeViewBox",
      active: false,
    },
  ],
};
